# Generated by Django 3.2 on 2021-05-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='SorlPhoto/%Y', verbose_name='IMAGE'),
        ),
    ]
